# Generated by Django 3.2.13 on 2022-05-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_choices_questions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choices',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='student_id',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='scores',
            old_name='topic_id',
            new_name='topic',
        ),
    ]
